### ISSUE TITLE
[1.12] Poof! crashes. (w/ latest forge 2187)

### ISSUE THREAD

**Issue by Migmag789** [Glitchfiend/ToughAsNails#288] opened 2017-07-02 08:01 UTC
Poof! crashes.
I'm looking at a expert mode to my modpack but there is a crash... And it's not cool... x(
[crash-2017-07-02_09.59.59-client.txt](https://github.com/Glitchfiend/ToughAsNails/files/1117671/crash-2017-07-02_09.59.59-client.txt)

**Comment by Adubbz** [comment] 2017-07-02 09:18
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/285

**Closed as completed by Adubbz** 2017-07-02 09:18 UTC
