### ISSUE TITLE
Standing on beds acts like you're outside

### ISSUE THREAD

**Issue by xhatz** [Glitchfiend/ToughAsNails#819] opened 2023-12-08 18:09 UTC
### What's the issue you encountered?

When you stand on a bed, or maybe even slabs, it counts as if you character were outside for the temperature, even if the house is heated, you will get very cold quickly.

It's same for half blocks, ladders...

### How can the issue be reproduced?

Stand on a bed and see the temperature changes.

### Mod Version

8.0.0.78

**Comment by Adubbz** [comment] 2023-12-08 22:15
Duplicate of #789

**Closed as completed by Adubbz** 2023-12-08 22:15 UTC
