### ISSUE TITLE
[1.12.2] Potion Status

### ISSUE THREAD

**Issue by BuilderDan** [Glitchfiend/ToughAsNails#384] opened 2017-11-07 20:44 UTC
All the potion status icons are black, not sure why...
![image](https://user-images.githubusercontent.com/19805371/32516777-5b58f13a-c3b9-11e7-9315-063eed7477c3.png)

**Comment by liach** [comment] 2017-11-07 20:47
Duplicate of #276

**Comment by BuilderDan** [comment] 2017-11-07 20:49
That's great, its still a big though.

**Closed as completed** 2017-11-07 21:27 UTC
