### ISSUE TITLE
status icons is missing (v1.12)

### ISSUE THREAD

**Issue by hologer** [Glitchfiend/ToughAsNails#390] opened 2017-11-19 11:48 UTC
![2017-11-19_13 33 23](https://user-images.githubusercontent.com/16763467/32990328-6ae53994-cd49-11e7-8e72-accd634255d9.png)

**Comment by Forstride** [comment] 2017-11-19 13:29
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/276

**Closed as completed by Forstride** 2017-11-19 13:29 UTC
