### ISSUE TITLE
Effect Textures Are Black

### ISSUE THREAD

**Issue by iWERTSQ** [Glitchfiend/ToughAsNails#360] opened 2017-10-01 13:06 UTC
Thirst, hypothermia and etc. their effects are black. I tried to run this mod alone and it didn't work neither, so no conflicts. Something is wrong with the mod.

Screenshot: 
![2017-10-01_16 05 05](https://user-images.githubusercontent.com/32433157/31054746-5ce5ab74-a6c2-11e7-83ff-d55c5ebf5e2b.png)

MC Version: 1.11.2
Mod Version: 2.1.0.65
Forge Version: 13.20.1.2476

**Comment by Adubbz** [comment] 2017-10-15 03:12
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/276

**Closed as completed by Adubbz** 2017-10-15 03:12 UTC
