### ISSUE TITLE
[1.11] Client Crash loading TAN

### ISSUE THREAD

**Issue by Morpheus1101** [Glitchfiend/ToughAsNails#138] opened 2016-11-20 10:36 UTC
crash report @ https://puu.sh/sonZD/db6921f8ba.txt

I may suspect BetterAgriculture is involved with this as well

**Comment by Adubbz** [comment] 2016-11-20 11:02
Duplicate of #137, also fixed in 2.0.2

**Closed as completed by Adubbz** 2016-11-20 11:02 UTC
