### ISSUE TITLE
Disable overheat/freezing system temporary

### ISSUE THREAD

**Issue by babacon88** [Glitchfiend/ToughAsNails#761] opened 2022-07-29 22:42 UTC
### Overview

the Temperature system already toned down since 1.18 but its just not for me and I want to enjoy other aspects of the mod. I'm tired of being frozen to death 30s into the game next to a fire or being overheated at the bottom of a lake.
It appears that wool and leaf suits are the only way to keep cool/warm, because campfire, or openfire, or burning down the whole forest still have you freeze and cover yourself with ice blocks/ down yourself under a lake still die from over heat. Wool and leaves are not always available, you need to find iron to get them, which takes more than a while. otherway is setting yourself on fire and drowning under powerdered snow. which also require iron and it takes a while to get. Hardcore gameplay is impossible unless you spawn to a village which provide iron. 
There should be better debuffs instead of just just damage our health and kills you in 10s

### Why would this feature be useful?

Temperature system is just broken

**Comment by Adubbz** [comment] 2022-07-29 22:44
Duplicate of #758

**Closed as not planned by Adubbz** 2022-07-29 22:44 UTC
Labels: feature
