### ISSUE TITLE
strange crash at game loading

### ISSUE THREAD

**Issue by 0Navis0** [Glitchfiend/ToughAsNails#274] opened 2017-06-22 22:02 UTC
I get a pretty strange crash at each time I try to load the game. It seems there an incompability with ExtraUtilities. I use TAN 1.11.2-2.1.0.39 and Forge 13.20.0.2315.  https://pastebin.com/YLeGyBfz

**Comment by Adubbz** [comment] 2017-06-23 00:55
Can you reproduce this with only ExtraUtilities and TAN installed? And can you please provide the log when that happens?

**Comment by 0Navis0** [comment] 2017-06-23 01:23
Here is the log https://pastebin.com/ZSDMsYLA

**Comment by 0Navis0** [comment] 2017-06-23 01:50
And no the crash doesn't occur when there is only TAN and ExtraUtilities, another mod is surely involved.

**Comment by Adubbz** [comment] 2017-06-23 01:52
I need to know the specific mod that causes this crash, because you have a *lot* of mods installed. Since this appears to be a problem with ASM it's not something I can easily track down otherwise.

**Comment by 0Navis0** [comment] 2017-06-23 01:53
The crash occurs since TAN-20.5.6. I will try to find the other mods which cause the crash, but it will be long and not easy with all the mods I have.

**Comment by Rinma** [comment] 2017-07-02 11:05
Found it. When i start TAN together with Extra Utils AND Random Things the game crashs at loading with this error message. When the game is started with only one of the to mods it's working.

Versions:
extrautils2-1.11.2-1.4.4
RandomThings-MC1.11.2-4.0
ToughAsNails-1.11.2-2.1.0.51

**Comment by asiekierka** [comment] 2017-07-06 09:57
@Adubbz https://asie.pl/Projects/Minecraft/Mods/EnvironmentChecker You might find this handy.

**Comment by Adubbz** [comment] 2017-07-09 03:15
Looks like this was fixed in a newer version of Random Things anyways, but thanks for the tip @asiekierka

**Closed as completed by Adubbz** 2017-07-09 03:15 UTC
