### ISSUE TITLE
Crash on launch, version 1.11.2-2.1.0.36

### ISSUE THREAD

**Issue by samuellapointe** [Glitchfiend/ToughAsNails#280] opened 2017-06-25 12:21 UTC
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.6-1.11.2.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.7.0.268-universal.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.6.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.11.2-1.2.2.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.3.8-universal.jar)
  LoadingPlugin (Quark-r1.2-93.jar)
  LoadingPlugin (RandomThings-MC1.11.2-4.0.jar)
  CTMCorePlugin (CTM-MC1.11.2-0.1.1.6.jar)
  TANLoadingPlugin (ToughAsNails-1.11.2-2.1.0.36-universal.jar)
  LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  ForgelinPlugin (Forgelin-1.4.2.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 6/25/17 8:18 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from extrautils2 (extrautils2)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/world/World.func_175727_C(Lnet/minecraft/util/math/BlockPos;)Z @53: ifeq
  Reason:
    Type 'toughasnails/api/season/Season' (current frame, stack[3]) is not assignable to integer
  Current Frame:
    bci: @53
    flags: { }
    locals: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season' }
    stack: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season', 'toughasnails/api/season/Season' }
  Bytecode:
    0x0000000: 2ab6 09bc 9a00 0503 ac2a 2bb6 02f1 9a00
    0x0000010: 0503 ac2a 2bb6 09be b601 802b b601 80a4
    0x0000020: 0005 03ac 2ab8 07d5 b907 db01 00b6 07e1
    0x0000030: 4d2a 2b2c 5999 0009 572a 2bb8 09c1 b809
    0x0000040: c5ac                                   
  Stackmap Table:
    same_frame(@9)
    same_frame(@19)
    same_frame(@36)

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetMethodRecursive(Unknown Source)
	at java.lang.Class.getMethod0(Unknown Source)
	at java.lang.Class.getMethod(Unknown Source)
	at com.rwtema.extrautils2.ExtraUtils2.<clinit>(ExtraUtils2.java:77)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:546)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:582)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:233)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1196502336 bytes (1141 MB) / 1994391552 bytes (1902 MB) up to 5592580096 bytes (5333 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms409m -Xmx6000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2315 Optifine OptiFine_1.11.2_HD_U_C2 88 mods loaded, 88 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2315-universal.jar) 
	UC	forge{13.20.0.2315} [Minecraft Forge] (forge-1.11.2-13.20.0.2315-universal.jar) 
	UC	advancedrocketrycore{1} [Advanced Rocketry Core] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UC	dmonsters{1.15} [Deadly Monsters] (1.11.2_deadly_monsters_1.5.jar) 
	UC	jei{4.5.0.289} [Just Enough Items] (jei_1.11.2-4.5.0.289.jar) 
	UC	abyssalcraft{1.9.4-pre-4} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.4-pre-4.jar) 
	UC	actuallyadditions{1.11.2-r110} [Actually Additions] (ActuallyAdditions-1.11.2-r110.jar) 
	UC	libvulpes{0.2.5.} [Vulpes library] (LibVulpes-1.11.2-0.2.5-universal.jar) 
	UC	advancedrocketry{1.2.2} [Advanced Rocketry] (AdvancedRocketry-1.11.2-1.2.2.jar) 
	UC	quark{r1.2-93} [Quark] (Quark-r1.2-93.jar) 
	UC	cofhcore{4.2.3} [CoFH Core] (CoFHCore-1.11.2-4.2.3.8-universal.jar) 
	UC	animania{1.1.5} [Animania] (animania-1.11.2-1.1.5.jar) 
	UC	forgelin{1.4.2} [Forgelin] (Forgelin-1.4.2.jar) 
	UC	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UC	chisel{MC1.11.2-0.0.11.16} [Chisel] (Chisel-MC1.11.2-0.0.11.16.jar) 
	UC	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UC	thedragonlib{1.11.2-3.2.2} [TheDragonLib] (thedragonlib-1.11.2-3.2.2.jar) 
	UC	armorplus{1.11.2-10.6.1.0} [ArmorPlus] (armorplus-1.11.2-10.6.1.0.jar) 
	UC	psi{r1.1-47} [Psi] (Psi-r1.1-47.jar) 
	UC	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UC	bibliocraft{2.3.2} [BiblioCraft] (BiblioCraft[v2.3.2][MC1.11.2].jar) 
	UC	biomesoplenty{6.2.0.2254} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.2.0.2254-universal.jar) 
	UC	blocklings{4.1.11} [WillR27's Blocklings] (Blocklings 4.1.11 - 1.11.2.jar) 
	UC	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1.jar) 
	UC	buildcraftlib{7.99.4} [BuildCraft Lib] (buildcraft-7.99.4.jar) 
	UC	buildcraftcore{7.99.4} [BuildCraft] (buildcraft-7.99.4.jar) 
	UC	buildcraftfactory{7.99.4} [BC Factory] (buildcraft-7.99.4.jar) 
	UC	buildcrafttransport{7.99.4} [BC Transport] (buildcraft-7.99.4.jar) 
	UC	buildcraftbuilders{7.99.4} [BC Builders] (buildcraft-7.99.4.jar) 
	UC	buildcraftenergy{7.99.4} [BC Energy] (buildcraft-7.99.4.jar) 
	UC	buildcraftrobotics{7.99.4} [BC Robotics] (buildcraft-7.99.4.jar) 
	UC	buildcraftsilicon{7.99.4} [BC Silicon] (buildcraft-7.99.4.jar) 
	UC	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UC	codechickenlib{2.7.0.268} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.7.0.268-universal.jar) 
	UC	ctm{MC1.11.2-0.1.1.6} [CTM] (CTM-MC1.11.2-0.1.1.6.jar) 
	UC	cyberware{alpha-0.2.9} [Cyberware] (cyberware-1.11.2-alpha-0.2.9.jar) 
	UC	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UC	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UC	dungeontactics{DT-0.11.7} [DungeonTactics] (DungeonTactics-1.11.2-0.11.7.jar) 
	UC	dsurround{3.4.5.6} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.5.6.jar) 
	UC	presets{3.4.5.6} [Presets!] (DynamicSurroundings-1.11.2-3.4.5.6.jar) 
	UC	embers{0.216} [Embers] (embers-0.216.jar) 
	UC	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0c.jar) 
	UC	environmentaltech{1.11.2-0.11.0d} [Environmental Tech] (environmentaltech-1.11.2-0.11.0d.jar) 
	UC	epicsiegemod{12.0.158} [Epic Siege Mod] (EpicSiegeMod-12.0.158.jar) 
	UE	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.4.jar) 
	UC	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UC	forestry{5.3.4.114} [Forestry] (forestry_1.11.2-5.3.4.114.jar) 
	UC	gravestone{1.7.3} [Gravestone Mod] (gravestone-1.7.3.jar) 
	UC	immersiveengineering{0.11-62} [Immersive Engineering] (ImmersiveEngineering-0.11-62.jar) 
	UC	inventorypets{1.4.9.5} [Inventory Pets] (inventorypets-1.11.2-1.4.9.5.jar) 
	UC	ironchest{1.11.2-7.0.24.809} [Iron Chest] (ironchest-1.11.2-7.0.24.809.jar) 
	UC	shadowmc{3.7.1} [ShadowMC] (ShadowMC-1.11.2-3.7.5.jar) 
	UC	largeveins{@VERSION@} [Large Veins] (LargeVeins-1.11-1.0.0.jar) 
	UC	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.0.4-1.11.2.jar) 
	UC	levels{r1.2.8} [Levels] (Levels 2-1.11.2-r1.2.8.jar) 
	UC	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
	UC	lostcities{0.0.8beta} [The Lost Cities] (lostcities-1.1x-0.0.8beta.jar) 
	UC	mekanism{9.3.2} [Mekanism] (Mekanism-1.11.2-9.3.2.307.jar) 
	UC	mekanismgenerators{9.3.2} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.2.307.jar) 
	UC	mekanismtools{9.3.2} [MekanismTools] (MekanismTools-1.11.2-9.3.2.307.jar) 
	UC	minecolonies{1.11.2-0.8.1784} [MineColonies] (minecolonies-universal-1.11.2-0.8.1784.jar) 
	UC	mowziesmobs{1.3.3} [Mowzie's Mobs] (mowziesmobs-1.3.3.jar) 
	UC	mw{1.10.3} [Modern Warfare] (mw-1.10.3_mc1.11.2.jar) 
	UC	nuclearcraft{2.2d} [NuclearCraft] (NuclearCraft-2.2d--1.11.2.jar) 
	UC	omlib{3.0.0-100} [OMLib] (omlib-1.11.2-3.0.0-100.jar) 
	UC	ompd{3.0.0-22} [Open Modular Passive Defense] (ompd-1.10.2-3.0.0-22.jar) 
	UC	openmodularturrets{3.0.0-158} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-158.jar) 
	UC	overlord{2.4.1} [Overlord] (Overlord-1.11.2-2.4.1.jar) 
	UC	randomthings{4.0} [Random Things] (RandomThings-MC1.11.2-4.0.jar) 
	UC	xreliquary{1.11.2-1.3.3.653} [Reliquary] (Reliquary-1.11.2-1.3.3.653.jar) 
	UC	reptilemod{3.6.2} [Reptile Mod] (reptilemod-1.11.2-3.6.2-68.jar) 
	UC	rftools{6.01} [RFTools] (rftools-1.1x-6.01.jar) 
	UC	ftrsquids{1.0} [Rocket Squids] (Rocket Squids 1.11.2-1.0.jar) 
	UC	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UC	roots{0.020} [Roots 2] (roots-2-0.020.jar) 
	UC	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar) 
	UC	teletubbies{1.4.2} [Teletubbies] (Teletubbies-1.11-1.4.2.jar) 
	UC	thermalfoundation{2.2.3} [Thermal Foundation] (ThermalFoundation-1.11.2-2.2.3.5-universal.jar) 
	UC	thermalexpansion{5.2.3} [Thermal Expansion] (ThermalExpansion-1.11.2-5.2.3.6-universal.jar) 
	UC	tinkertoolleveling{1.11.2-1.0.1.DEV.641b08f} [Tinkers Tool Leveling] (TinkerToolLeveling-1.11.2-1.0.1.jar) 
	UC	toughasnails{2.1.0.36} [Tough As Nails] (ToughAsNails-1.11.2-2.1.0.36-universal.jar) 
	UC	waddles{0.5.2} [Waddles] (Waddles-1.11.2-0.5.2.jar) 
	UC	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.6-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CCLCorePlugin (CodeChickenLib-1.11.2-2.7.0.268-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.6.jar)
  org.blockartistry.DynSurround.asm.Transformer
AdvancedRocketryPlugin (AdvancedRocketry-1.11.2-1.2.2.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
CoFH Loading Plugin (CoFHCore-1.11.2-4.2.3.8-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
LoadingPlugin (Quark-r1.2-93.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.11.2-4.0.jar)
  lumien.randomthings.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.11.2-0.1.1.6.jar)
  team.chisel.ctm.client.asm.CTMTransformer
TANLoadingPlugin (ToughAsNails-1.11.2-2.1.0.36-universal.jar)
  toughasnails.asm.transformer.CropDecayTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.4.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.53' Renderer: 'GeForce GTX 770/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.11.2_HD_U_C2
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-v11.0.zip
	OpenGlVersion: 4.5.0 NVIDIA 376.53
	OpenGlRenderer: GeForce GTX 770/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by samuellapointe** [comment] 2017-06-25 12:23
Disabling either Extra Utilities 2 or TAN solves the crash

**Comment by Adubbz** [comment] 2017-06-25 13:58
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/274

**Closed as completed by Adubbz** 2017-06-25 13:58 UTC
