### ISSUE TITLE
Going to Nether sets hearts to 10 rather then 5 and going back to overworld keeps it as 5 unless player dies

### ISSUE THREAD

**Issue by ghost** [Glitchfiend/ToughAsNails#218] opened 2017-03-29 19:35 UTC
Title says it all
If You go to Nether, the hearts are 10 rather than the 5 which You start with
Then returning from the nether to the over

**Comment by ghost** [comment] 2017-03-29 19:36
Sorry, hit enter by mistake
returning from the nether to the overworld, it keeps them as 10 unless player dies

**Comment by Adubbz** [comment] 2017-03-29 20:13
This is a duplicate of this issue https://github.com/Glitchfiend/ToughAsNails/issues/42

**Closed as completed by Adubbz** 2017-03-29 20:13 UTC
