### ISSUE TITLE
ModConfig.java causes null pointer exception when adding drinks

### ISSUE THREAD

**Issue by daniel-widrick** [Glitchfiend/ToughAsNails#623] opened 2019-02-25 06:12 UTC
https://github.com/Glitchfiend/ToughAsNails/blob/40e5aa7e993c6f1fa3c3107491e45fbd1934d802/src/main/java/toughasnails/init/ModConfig.java#L75

This line is currently causing a nullpointerexception while I am trying to ad drinks to the drink_stats.json.

I've probably misspelled an item name but can't figure out which one as the crash dump shows no relevant info.

My assumption is that wrapping the pieces of the populateDataMap() for loop in a try catch will allow the mod to log any failed items and display helpful log messages.

I'm working on a java dev environment now to look into this further..

**Comment by CREEATION** [comment] 2019-02-25 22:48
Can confirm. Even just changing the default `minecraft:milk_bucket` to `minecraft:melon_slice` doesn't work.

**Comment by daniel-widrick** [comment] 2019-02-26 05:39
So... I was able to get the mod to ignore invalid item names... I am having a heck of a time divining how to log the item name though

https://github.com/daniel-widrick/ToughAsNails/commit/5d00c36a5c0701eee955d279ab0d6ee1c067b64b

I was able to do some fancy counting and came up with this list: (missing sodas)
https://pastebin.com/SGMWhKTu

Will have to read up on these lambdas and weird hashmaps..

**Comment by CREEATION** [comment] 2019-03-10 15:00
This is a crash dump related to this issue, btw: https://paste.dimdev.org/dujoworete.mccrash

**Comment by CREEATION** [comment] 2019-03-25 13:32
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/595

**Closed as completed** 2021-02-05 23:04 UTC
