### ISSUE TITLE
temperature of hot spring water

### ISSUE THREAD

**Issue by FELITH** [Glitchfiend/ToughAsNails#237] opened 2017-05-05 11:26 UTC
bop's hot spring water should give heat not cold.
ToughAsNails-1.11-2.0.5.jar
BiomesOPlenty-1.11.2-6.0.2.2157-universal.jar

**Comment by dcbartlett** [comment] 2017-06-14 04:37
Duplicate of: https://github.com/Glitchfiend/ToughAsNails/issues/163

**Comment by Forstride** [comment] 2017-06-22 17:12
Added this in the latest update to 1.12

**Closed as completed by Forstride** 2017-06-22 17:12 UTC

**Comment by Woody-0w0** [comment] 2021-04-29 01:40
Nicer to add config list for fluid block on which give heat
