### ISSUE TITLE
items from other mods can't light campfire

### ISSUE THREAD

**Issue by rikott** [Glitchfiend/ToughAsNails#492] opened 2018-04-23 01:09 UTC
Wondering if we could get a config option to enable items like a firestarter (from roots mod) or a box of matches (from realistic torches mod) to have the ability to light the campfire?

**Comment by Forstride** [comment] 2018-04-23 06:01
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/352

**Closed as completed by Forstride** 2018-04-23 06:01 UTC
