### ISSUE TITLE
Unknown 

### ISSUE THREAD

**Issue by Jop890** [Glitchfiend/ToughAsNails#625] opened 2019-03-03 18:49 UTC
Problem is this
---- Minecraft Crash Report ----

WARNING: coremods are present:
BCModPlugin (backpacks+1.12.2+-+3.5.4.jar)
LoadingPlugin (replaymod-1.12.2-2.1.4.jar)
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
OpenEyePlugin (OpenEye.jar)
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/3/19 1:36 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tough As Nails (toughasnails)
Caused by: java.lang.NullPointerException
at toughasnails.init.ModConfig.lambda$init$0(ModConfig.java:64)
at toughasnails.init.ModConfig$$Lambda$309/303868505.apply(Unknown Source)
at toughasnails.init.ModConfig.populateDataMap(ModConfig.java:92)
at toughasnails.init.ModConfig.init(ModConfig.java:64)
at toughasnails.core.ToughAsNails.init(ToughAsNails.java:83)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1051708472 bytes (1002 MB) / 1811939328 bytes (1728 MB) up to 2147483648 bytes (2048 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2768 51 mods loaded, 50 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID                      | Version       | Source                                           | Signature                                |
|:----- |:----------------------- |:------------- |:------------------------------------------------ |:---------------------------------------- |
| UCHI  | minecraft               | 1.12.2        | minecraft.jar                                    | None                                     |
| UCHI  | mcp                     | 9.42          | minecraft.jar                                    | None                                     |
| UCHI  | FML                     | 8.0.99.99     | forge-1.12.2-14.23.5.2768.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHI  | forge                   | 14.23.5.2768  | forge-1.12.2-14.23.5.2768.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHI  | creativecoredummy       | 1.0.0         | minecraft.jar                                    | None                                     |
| UCHI  | OpenEye                 | 0.8           | OpenEye.jar                                      | None                                     |
| UCHI  | obfuscate               | 0.2.6         | minecraft.jar                                    | None                                     |
| UCHI  | replaymod-compat        | 1.12.2-2.1.4  | replaymod-1.12.2-2.1.4.jar                       | None                                     |
| UCHI  | replaymod               | 1.12.2-2.1.4  | replaymod-1.12.2-2.1.4.jar                       | None                                     |
| UCHI  | replaymod-editor        | 1.12.2-2.1.4  | replaymod-1.12.2-2.1.4.jar                       | None                                     |
| UCHI  | replaymod-extras        | 1.12.2-2.1.4  | replaymod-1.12.2-2.1.4.jar                       | None                                     |
| UCHI  | replaymod-online        | 1.12.2-2.1.4  | replaymod-1.12.2-2.1.4.jar                       | None                                     |
| UCHI  | replaymod-recording     | 1.12.2-2.1.4  | replaymod-1.12.2-2.1.4.jar                       | None                                     |
| UCHI  | replaymod-render        | 1.12.2-2.1.4  | replaymod-1.12.2-2.1.4.jar                       | None                                     |
| UCHI  | replaymod-replay        | 1.12.2-2.1.4  | replaymod-1.12.2-2.1.4.jar                       | None                                     |
| UCHI  | replaymod-simplepathing | 1.12.2-2.1.4  | replaymod-1.12.2-2.1.4.jar                       | None                                     |
| UCHI  | backpacks16840          | 3.5.4         | backpacks+1.12.2+-+3.5.4.jar                     | None                                     |
| UCHI  | biomestaff              | 1.0.0         | BiomeStaff-1.12.2-1.0.0.jar                      | None                                     |
| UCHI  | cdm                     | 0.4.1         | cdm-0.4.1-mc1.12.2.jar                           | None                                     |
| UCHI  | cdmcalculator           | 2.4           | CalculatorPlus-2.4+(0.4.0).jar                   | None                                     |
| UCHI  | cameraobscura           | 0.0.1         | CameraObscura-1.0.3.jar                          | None                                     |
| UCHI  | cfm                     | 5.13.0        | cfm-5.13.0-mc1.12.2.jar                          | None                                     |
| UCHI  | craysoft-office-mod     | 0.0.8         | Craysoft+Office+Addon+Version+0.0.8+[1.12.2].jar | None                                     |
| UCHI  | creativecore            | 1.9.9         | CreativeCore_v1.9.22_mc1.12.2.jar                | None                                     |
| UCHI  | modcurrency             | 1.12-1.3.2    | Currency-1.12.0-1.3.2.jar                        | None                                     |
| UCHI  | customnpcs              | 1.12          | CustomNPCs_1.12.2(30Jan19).jar                   | None                                     |
| UCHI  | deviceai                | 2.4           | Device+AI-2.4.jar                                | None                                     |
| UCHI  | emoticons               | 0.2.1         | emoticons-0.2.1-1.12.2.jar                       | None                                     |
| UCHI  | cgm                     | 0.9.2         | guns-0.9.2-1.12.2.jar                            | None                                     |
| UCHI  | ichunutil               | 7.1.4         | iChunUtil-1.12.2-7.1.4.jar                       | None                                     |
| UCHI  | ism                     | 2.5 MC-1.12.2 | ism-2.5 MC-1.12.2.jar                            | None                                     |
| UCHI  | jei                     | 4.13.1.225    | jei_1.12.2-4.13.1.225.jar                        | None                                     |
| UCHI  | kda                     | 0.0.2         | kda-0.0.3.jar                                    | None                                     |
| UCHI  | levelup2                | ${version}    | Level+Up!+2-1.1.22-1.12.jar                      | None                                     |
| UCHI  | lightswitch             | 1.1.2         | lightswitch-1.1.2-mc1.12.2.jar                   | None                                     |
| UCHI  | mclib                   | 1.0           | mclib-1.0-1.12.2.jar                             | None                                     |
| UCHI  | minetraps               | 1.0.3         | MineTraps-1.12.2-(v.1.0.3).jar                   | None                                     |
| UCHI  | musiccraft              | 3.2.3         | MusicCraft-3.2.3.jar                             | None                                     |
| UCHI  | opframe                 | 1.4.0         | OnlinePicFrame_v1.4.18_mc1.12.2.jar              | None                                     |
| UCHI  | osmw                    | 0.1.1         | osmw-0.1.1.jar                                   | None                                     |
| UCHI  | ptrmodellib             | 1.0.3         | PTRLib-1.0.3.jar                                 | None                                     |
| UCHI  | redstoneflux            | 2.0.1         | RedstoneFlux-1.12-2.0.1.2-universal.jar          | d4f1503fbacd9b9fb767720420c5395104239ec9 |
| UCHI  | sekcphysics             | 0.1.0         | sekcphysics-0.1.0.jar                            | None                                     |
| UCHI  | sereneseasons           | 1.2.15        | SereneSeasons-1.12.2-1.2.15-universal.jar        | None                                     |
| UCHEE | toughasnails            | 3.1.0.139     | ToughAsNails-1.12.2-3.1.0.139-universal.jar      | None                                     |
| UCH   | vehicle                 | 0.36.1        | vehicle-mod-0.36.1-1.12.2.jar                    | None                                     |
| UCH   | walljump                | 1.12.2-1.2.1  | walljump-1.12.2-1.2.1.jar                        | None                                     |
| UCH   | xaerominimap            | 1.15.8        | Xaeros_Minimap_1.15.8_Forge_1.12.jar             | None                                     |
| UCH   | xlfoodmod               | 1.12.2-1.8.1  | XL-Food-Mod-1.12.2-1.8.1.jar                     | None                                     |
| UCH   | trapexpansion           | 1.0.0         | trapexpansion-1.0.0.jar                          | None                                     |
| UD    | emoticons_core          | 0.2.1         | minecraft.jar                                    | None                                     |

Loaded coremods (and transformers): 
BCModPlugin (backpacks+1.12.2+-+3.5.4.jar)
brad16840.core.ClassTransformer
LoadingPlugin (replaymod-1.12.2-2.1.4.jar)

ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
OpenEyePlugin (OpenEye.jar)
openeye.asm.MultiTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
sereneseasons.asm.transformer.EntityRendererTransformer
sereneseasons.asm.transformer.WorldTransformer
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)

EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
mchorse.emoticons.core.EmoCoreClassTransformer
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GTX 1070/PCIe/SSE2'

**Comment by CREEATION** [comment] 2019-03-25 13:33
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/595

**Comment by ilvrak** [comment] 2019-06-06 02:50
try to disable other mods and see on what config MC loads with TAN.
repeat until you locate one mod caused crash.
that you may locate incompatibility.

**Closed as completed** 2021-02-05 23:04 UTC
