### ISSUE TITLE
[Suggestion] Configure thirst values for other mod's foods

### ISSUE THREAD

**Issue by Luke616** [Glitchfiend/ToughAsNails#270] opened 2017-06-21 21:31 UTC
Any way you guys could add a section in the configs to add thirst values to other mod's foods / edit existing thirst values? Playing with mods like Pam's that add drink items, and it feels silly to drink a smoothie and have it only refill hunger. Would love to be able to edit these values.

Thanks!

**Comment by Forstride** [comment] 2017-06-22 00:34
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/9

**Closed as completed by Forstride** 2017-06-22 00:34 UTC
