### ISSUE TITLE
Thirst effect is pointless

### ISSUE THREAD

**Issue by Efimero** [Glitchfiend/ToughAsNails#258] opened 2017-05-29 20:45 UTC
when you drink dirty water you get thirsty, but the penalty lasts 30 seconds and doesn't even drain a single drop from the bar
imo, the debuff should last at least 10 minutes, if you're sick from drinking bad water, you should have penalties
it could be configurable, both the times of the debuff for dirty and filtered water, the chances and it would also be nice if it could cause hunger too, with the same config options <3

**Comment by KnightMiner** [comment] 2017-05-29 20:49
10 minutes seems way too long given how hard to get clean water is before you can filter it. It does seem to be lacking negative effects though.

**Comment by Efimero** [comment] 2017-05-29 21:16
you can keep drinking water while the effect is running, so it is unlikely it will kill you
I don't know the right time, but it should be enough that the thirst would drain more than it was recovered from drinking the dirty water, minimum

**Comment by tyler489** [comment] 2017-05-30 23:41
Or you could make it while drinking more dirty water increases the thirst lv or length of thirst if you are already thirdty

**Comment by Forstride** [comment] 2017-05-31 00:06
The Thirst effect is meant to be like the vanilla Hunger effect, although right now, it still doesn't seem to drain thirst fast enough, even though the values should be the exact same.

**Comment by Efimero** [comment] 2017-05-31 14:03
@Forstride I assume that is because the amount of thirst is a bigger number than hunger
you don't get more granular than half a hunger in vanilla, so the max must be 20, but thirst seems to have quarters or so, so it's probably more than 40
the same amount of decrease would have less of an effect on the percentage of the total

**Comment by Forstride** [comment] 2017-06-22 14:57
Just gonna close this since it's kind of a duplicate of this issue: https://github.com/Glitchfiend/ToughAsNails/issues/111

**Closed as completed by Forstride** 2017-06-22 14:57 UTC
