### ISSUE TITLE
Dying carries a lot of status effects such as Hyperthermia and thirst

### ISSUE THREAD

**Issue by Siigari** [Glitchfiend/ToughAsNails#130] opened 2016-10-15 12:22 UTC
So I fell in lava and died to hyperthermia. When I respawned, I still had hyperthermia status for a full 1:30, and I died again. Also, thirst status carries over from death.

I believe these things need to be fixed. Thanks!

**Comment by Forstride** [comment] 2017-06-22 17:19
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/108

**Closed as completed by Forstride** 2017-06-22 17:19 UTC
