### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by Swelem** [Glitchfiend/ToughAsNails#363] opened 2017-10-07 00:06 UTC
Hey, so there are a lot of compatibility issues with weather2 like:
Rain collectors only fill up if vanilla says rain and don't respond to weather2 rain
In winter, snow doesn't fall from the sky and doesn't accumulate on the ground.

To sum it up weather2 weather doesn't affect tough as nails.
Thank you for fixing this in advance

**Comment by Adubbz** [comment] 2017-10-07 00:16
Duplicate of https://github.com/Glitchfiend/ToughAsNails/issues/149

**Closed as completed by Adubbz** 2017-10-07 00:16 UTC
