### ISSUE TITLE
game crash on boot (mod conflict?)

### ISSUE THREAD

**Issue by lolwutskis** [Glitchfiend/ToughAsNails#286] opened 2017-06-30 14:19 UTC
me: 6/30/17 10:07 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from extrautils2 (extrautils2)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/world/World.func_175727_C(Lnet/minecraft/util/math/BlockPos;)Z @53: ifeq
  Reason:
    Type 'toughasnails/api/season/Season' (current frame, stack[3]) is not assignable to integer
  Current Frame:
    bci: @53
    flags: { }
    locals: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season' }
    stack: { 'net/minecraft/world/World', 'net/minecraft/util/math/BlockPos', 'toughasnails/api/season/Season', 'toughasnails/api/season/Season' }
  Bytecode:
    0x0000000: 2ab6 09c1 9a00 0503 ac2a 2bb6 02f1 9a00
    0x0000010: 0503 ac2a 2bb6 09c3 b601 802b b601 80a4
    0x0000020: 0005 03ac 2ab8 07da b907 e001 00b6 07e6
    0x0000030: 4d2a 2b2c 5999 0009 572a 2bb8 09c6 b809
    0x0000040: caac                                   
  Stackmap Table:
    same_frame(@9)
    same_frame(@19)
    same_frame(@36)

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at com.rwtema.extrautils2.ExtraUtils2.<clinit>(ExtraUtils2.java:77)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:552)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:582)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:233)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by KnightMiner** [comment] 2017-06-30 16:29
Duplicate of #274

**Closed as completed** 2017-06-30 17:45 UTC

**Comment by lolwutskis** [comment] 2017-06-30 18:43
thank you kindly
